name: obiwow2025_dl_for_dti
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.25
  - pandas>=2.0
  - requests>=2.30
  - tqdm>=4.65
  - scikit-learn>=1.3
  - pytorch>=2.2
  - torchvision>=0.18
  - pip:
      - typing-extensions
      - notebook
